apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy44
  labels:
    app: autodeploy44
  namespace: namespace-workflow-1714403529187
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy44
  template:
    metadata:
      labels:
        app: autodeploy44
    spec:
      containers:
        - name: autodeploy44
          image: acrworkflow1714403529187.azurecr.io/image-workflow-1714403529187:latest
          ports:
            - containerPort: 5000